### ISSUE TITLE
crash on first run

### ISSUE THREAD

**Issue by ravendyg** [ravendyg/gortrans-server-2#9]
app.tsx:69 TypeError: Cannot read property 'stopsData' of null
    at https://www.test.nskgortrans.info/app.min.js:119:14
From previous event:
    at Object.<anonymous> (https://www.test.nskgortrans.info/app.min.js:115:95)
    at __webpack_require__ (https://www.test.nskgortrans.info/app.min.js:21:30)
    at https://www.test.nskgortrans.info/app.min.js:41:18
    at https://www.test.nskgortrans.info/app.min.js:44:10 "get timestamp from localForage"

**Comment by ravendyg** [comment]
probably done
